language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install

script:
  - vendor/bin/jsonlint channel_set.json
  - vendor/bin/jsonlint custom_fields/**/*

before_deploy:
  - rm -rf ./.editorconfig
  - rm -rf ./.gitignore
  - rm -rf ./.travis.yml
  - rm -rf ./vendor/
  - rm -rf ./composer.*
  - rm -rf ./README.md
  - zip -r 'game' .

deploy:
  provider: releases
  api_key:
    secure: nBhMcBwHJ2wG8prrR+GaGJO0sfhNRbJQ6v+C8fSZuASYIQO0wgoywQOOkt5EmoQiMPXk9gF7dc82RxSBLivu+bRAUyR53CSyVXV8dNltJd9987SPQZhV1TChLupOaxfltUMmfUGI6Otq64XBJikNqZKpPUKpfOyGHialwQkObj2r3OH3jdw6fIWFbNDXAiLrRwlhzzMZxTcTXqbBcg4MSe+TqvXRm0Xb6ZREI+mGpMlt8ZAvL2Hm92YJH7imTFcEjDG2s1obJwIY1/f8C/RJuPG9kUFD0rXn7iuQzyqHSdJUavF4+Jk07edOoZnYQKS5jIEYxfenLdXpMrzsYzHnTFINpHNQ0b1EtUdkxwwIGHp+ErPutfyijd4SRox47oz64hYvrcef/YVfhrrC0i58BxzENJUbFaiJ7oPgrPfZ9SjBJaGVTTOXeG0XbjSJab3YvVTDTvNxI5ZUlkINnjxjK8u++uWaMd62f29AafrM/K/2HE0eB4asbr/xLEaZL1T/MypilQ8ZVsnkM1Qm/Igt/PacVCVz+UR+NRyHdsBYOwAwze+IhvUQt/upNLal0vkRwRygXqYWAdzVLsxeDrNF8Z5yh7PYpF18G54TuY9q+6kWc8ooHZt8iGQh/vT6Xuhd8xnwpX4mWUPEs5En8wLotQkPmx+vl737Kvu0OKvdHBA=
  file: game.zip
  on:
    php: 7.0
    tags: true
    repo: EllisLab/channel-set-game
